name: Try reading a secret

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Time to read the secret
        shell: bash
        run: |
          echo "The secret variable name is : SAMPLE "
          echo "The contents is ${{ secrets.SAMPLE }}"
